# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoPEC
                A QGIS plugin [Generated by Plugin Builder]

 GeoPEC Linha - Controle de qualidade cartográfica (acurácia posicional
 utilizando feições lineares).
 GeoPEC Linha - Spatial Data Quality (positional accuracy from linear
 feature)

  -------------------
        begin             : 2019-06-13
        copyright         : (C) 2019 by Afonso de Paula dos Santos,
                                        Patrícia dos Santos Teixeira
        email             : afonso.santos@ufv.br, patricia.s.teixeira@ufv.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geopec class from file geopec.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geopec import geopec
    return geopec(iface)
